// Comprehensive Engineering Materials Dataset
// Supports: metals, alloys, ceramics, polymers, composites, semiconductors, advanced materials
// All properties are fully typed and identified as demonstration handbook reference data.

import { MaterialModel } from './materialModel';

export const MASTER_MATERIALS_DATA: MaterialModel[] = [
  // ==========================================
  // 1. METALS (Pure Elemental Metals)
  // ==========================================
  {
    id: 'cu-ofhc',
    name: 'Oxygen-Free High Conductivity Copper',
    nameAr: 'نحاس نقي فائق التوصيل خالي من الأكسجين',
    designation: 'OFHC Copper C10100 (99.99% Cu)',
    category: 'metals',
    subCategory: 'Precious & High-Conductivity Metals',
    formula: 'Cu',
    density: 8.94,
    hardness: { value: 65, scale: 'HV', approxHV: 65 },
    tensileStrength: 240,
    yieldStrength: 70,
    elasticModulus: 117,
    poissonRatio: 0.34,
    thermalConductivity: 391.0,
    meltingPoint: 1083,
    electricalConductivity: 5.86e7, // ~101% IACS
    corrosionResistance: 'High',
    thermalExpansion: 16.5,
    crystalStructure: 'FCC (Face-Centered Cubic)',
    maxServiceTemp: 200,
    description: 'High-purity wrought copper with supreme electrical and thermal conductivity, immune to hydrogen embrittlement under reducing atmospheres.',
    descriptionAr: 'نحاس مطاوع عالي النقاوة يمتاز بتوصيل كهربائي وحراري فائق ومناعة ضد التقصف الهيدروجيني.',
    applications: ['Particle accelerator cavities', 'Vacuum tube anodes', 'Cryogenic thermal straps', 'High-power busbars'],
    composition: { Cu: '99.99%', O: '<0.0005%' },
    isDemonstration: true,
    dataSource: 'CDA Copper Development Assoc. / ASM Handbook Vol 2. Demonstration data.',
  },
  {
    id: 'ti-cp-grade1',
    name: 'Commercially Pure Titanium Grade 1',
    nameAr: 'تيتانيوم نقي تجاريًا - رتبة 1',
    designation: 'CP-Ti Grade 1 (UNS R50250)',
    category: 'metals',
    subCategory: 'Refractory & Reactive Metals',
    formula: 'Ti',
    density: 4.51,
    hardness: { value: 120, scale: 'HV', approxHV: 120 },
    tensileStrength: 240,
    yieldStrength: 170,
    elasticModulus: 103,
    poissonRatio: 0.36,
    thermalConductivity: 21.6,
    meltingPoint: 1668,
    electricalConductivity: 2.38e6,
    corrosionResistance: 'Excellent',
    thermalExpansion: 8.6,
    crystalStructure: 'HCP (Hexagonal Close-Packed, α-phase)',
    maxServiceTemp: 315,
    description: 'The softest and most ductile unalloyed titanium offering supreme cold formability, resistance to chlorine attack, and stable bio-inertness.',
    descriptionAr: 'أنعم وأنقى درجات التيتانيوم التجاري غير المسبوك، يوفر قابلية تشكيل بارد فائقة ومقاومة للأكسدة والتآكل البيولوجي.',
    applications: ['Plate heat exchangers', 'Chemical desulfurization vessels', 'Anodizing racks', 'Deep-sea sensor housings'],
    composition: { Ti: '99.5% min', Fe: '0.20% max', O: '0.18% max' },
    isDemonstration: true,
    dataSource: 'ASTM B265 / ASM Handbook Vol 2. Demonstration data.',
  },
  {
    id: 'tungsten-pure',
    name: 'Pure Wrought Tungsten',
    nameAr: 'تنجستن مطاوع عالي النقاوة',
    designation: 'W-99.95% (UNS R07005)',
    category: 'metals',
    subCategory: 'Refractory Metals',
    formula: 'W',
    density: 19.25,
    hardness: { value: 450, scale: 'HV', approxHV: 450 },
    tensileStrength: 980,
    yieldStrength: 750,
    elasticModulus: 411,
    poissonRatio: 0.28,
    thermalConductivity: 174.0,
    meltingPoint: 3422,
    electricalConductivity: 1.82e7,
    corrosionResistance: 'Very High',
    thermalExpansion: 4.5,
    crystalStructure: 'BCC (Body-Centered Cubic)',
    maxServiceTemp: 2200,
    description: 'Refractory metal with the highest melting point of all elements, very high density, high elastic modulus, and lowest thermal expansion coefficient.',
    descriptionAr: 'معدن حراري يمتاز بأعلى نقطة انصهار بين كافة العناصر وكثافة عالية ومقاومة فائقة للحرارة العالية.',
    applications: ['Rocket nozzle throat liners', 'X-ray tube rotating targets', 'High-temperature furnace elements', 'Radiation shielding collimators'],
    composition: { W: '99.95% min' },
    isDemonstration: true,
    dataSource: 'Plansee Technical Bulletin / Callister Materials Science. Demonstration data.',
  },
  {
    id: 'aluminum-pure-1050',
    name: 'Pure Aluminum 1050-O',
    nameAr: 'ألومنيوم نقي 1050-O',
    designation: 'Al 1050-O (UNS A91050)',
    category: 'metals',
    subCategory: 'Light Metals',
    formula: 'Al',
    density: 2.70,
    hardness: { value: 20, scale: 'HB', approxHV: 20 },
    tensileStrength: 75,
    yieldStrength: 28,
    elasticModulus: 69,
    poissonRatio: 0.33,
    thermalConductivity: 231.0,
    meltingPoint: 660,
    electricalConductivity: 3.5e7,
    corrosionResistance: 'Very High',
    thermalExpansion: 24.0,
    crystalStructure: 'FCC (Face-Centered Cubic)',
    maxServiceTemp: 150,
    description: 'High-purity commercial aluminum with low density, high thermal and electrical conductivity, and high atmospheric corrosion resistance.',
    descriptionAr: 'ألومنيوم تجاري عالي النقاوة ذو كثافة منخفضة وتوصيل حراري وكهربائي ممتاز ومقاومة للصدأ الجوي.',
    applications: ['Food packaging foil', 'Chemical transfer piping', 'Architectural flashings', 'Capacitor foil'],
    composition: { Al: '99.5% min', Fe: '0.4% max', Si: '0.25% max' },
    isDemonstration: true,
    dataSource: 'Aluminum Association Yellow Book. Demonstration data.',
  },
  {
    id: 'nickel-200',
    name: 'Commercially Pure Nickel 200',
    nameAr: 'نيكل نقي تجاريًا 200',
    designation: 'Nickel 200 (UNS N02200)',
    category: 'metals',
    subCategory: 'Corrosion-Resistant Metals',
    formula: 'Ni',
    density: 8.89,
    hardness: { value: 110, scale: 'HV', approxHV: 110 },
    tensileStrength: 460,
    yieldStrength: 150,
    elasticModulus: 207,
    poissonRatio: 0.31,
    thermalConductivity: 70.2,
    meltingPoint: 1446,
    electricalConductivity: 1.04e7,
    corrosionResistance: 'Excellent',
    thermalExpansion: 13.3,
    crystalStructure: 'FCC (Face-Centered Cubic)',
    maxServiceTemp: 315,
    description: 'Commercially pure nickel renowned for supreme resistance to caustic alkalis (NaOH, KOH) and good magnetostrictive properties.',
    descriptionAr: 'نيكل نقي يمتاز بمقاومة استثنائية للقلويات الحارقة وهيدروكسيدات الصوديوم.',
    applications: ['Caustic soda evaporators', 'Synthetic fiber spinnerets', 'Hydrogen fuel cell electrodes'],
    composition: { Ni: '99.0% min', C: '0.15% max' },
    isDemonstration: true,
    dataSource: 'Special Metals Corp Specification / ASME SB-160. Demonstration data.',
  },

  // ==========================================
  // 2. ALLOYS (Ferrous, Non-Ferrous & Superalloys)
  // ==========================================
  {
    id: 'ti-6al-4v',
    name: 'Titanium Grade 5 (Ti-6Al-4V)',
    nameAr: 'سبيكة التيتانيوم رتبة 5',
    designation: 'Ti-6Al-4V Annealed (UNS R56400)',
    category: 'alloys',
    subCategory: 'Titanium Alloys',
    formula: 'Ti-6Al-4V',
    density: 4.43,
    hardness: { value: 340, scale: 'HV', approxHV: 340 },
    tensileStrength: 950,
    yieldStrength: 880,
    elasticModulus: 114,
    poissonRatio: 0.34,
    thermalConductivity: 6.7,
    meltingPoint: 1660,
    electricalConductivity: 5.6e5,
    corrosionResistance: 'Excellent',
    thermalExpansion: 8.6,
    crystalStructure: 'Dual phase: α (HCP) + β (BCC)',
    maxServiceTemp: 400,
    description: 'The workhorse α-β titanium alloy offering high strength-to-weight ratio, outstanding fracture toughness, and superior biocompatibility via stable TiO2 passive oxide film.',
    descriptionAr: 'سبيكة التيتانيوم الرائدة عالميًا في الطيران والطب الحيوي، تجمع المتانة العالية وخفة الوزن والمقاومة الكيميائية.',
    applications: ['Aerospace turbine blades', 'Airframe structural fasteners', 'Orthopedic and dental implants', 'Marine high-stress components'],
    composition: { Ti: 'Balance', Al: '5.5-6.75%', V: '3.5-4.5%', Fe: '0.4% max' },
    isDemonstration: true,
    dataSource: 'ASM Materials Handbook Vol 2 / ASTM B348. Demonstration data.',
  },
  {
    id: 'ss-316l',
    name: 'Austenitic Stainless Steel 316L',
    nameAr: 'فولاذ مقاوم للصدأ أوستنيتي 316L',
    designation: 'AISI 316L / EN 1.4404 (UNS S31603)',
    category: 'alloys',
    subCategory: 'Stainless Steels',
    formula: 'Fe-18Cr-12Ni-2.5Mo',
    density: 8.00,
    hardness: { value: 165, scale: 'HV', approxHV: 165 },
    tensileStrength: 580,
    yieldStrength: 290,
    elasticModulus: 193,
    poissonRatio: 0.30,
    thermalConductivity: 16.3,
    meltingPoint: 1400,
    electricalConductivity: 1.35e6,
    corrosionResistance: 'Very High',
    thermalExpansion: 16.0,
    crystalStructure: 'FCC (Austenite, γ-Fe)',
    maxServiceTemp: 870,
    description: 'Low-carbon molybdenum-bearing austenitic stainless steel providing enhanced resistance to pitting and crevice corrosion in chloride and acidic environments.',
    descriptionAr: 'فولاذ مقاوم للصدأ منخفض الكربون مع الموليبدينوم لمقاومة التآكل النقري في البيئات البحرية والحمضية.',
    applications: ['Chemical processing reactors', 'Marine hardware', 'Surgical devices', 'Pharmaceutical pipework'],
    composition: { Fe: 'Balance', Cr: '16.0-18.0%', Ni: '10.0-14.0%', Mo: '2.0-3.0%', C: '0.03% max' },
    isDemonstration: true,
    dataSource: 'ASTM A240 / ASM Specialty Handbook: Stainless Steels. Demonstration data.',
  },
  {
    id: 'inconel-718',
    name: 'Nickel Superalloy 718',
    nameAr: 'سبيكة النيكل الفائقة إنكونيل 718',
    designation: 'Inconel 718 Precipitation Hardened (UNS N07718)',
    category: 'alloys',
    subCategory: 'Nickel Superalloys',
    formula: 'Ni-Cr-Fe-Nb-Mo',
    density: 8.19,
    hardness: { value: 420, scale: 'HV', approxHV: 420 },
    tensileStrength: 1375,
    yieldStrength: 1100,
    elasticModulus: 205,
    poissonRatio: 0.29,
    thermalConductivity: 11.4,
    meltingPoint: 1336,
    electricalConductivity: 8.0e5,
    corrosionResistance: 'Excellent',
    thermalExpansion: 13.0,
    crystalStructure: 'FCC matrix (γ) with γ" [Ni3Nb] coherent precipitates',
    maxServiceTemp: 700,
    description: 'Precipitation-hardenable nickel-chromium alloy designed for high yield strength, creep rupture properties, and fatigue life at temperatures up to 700°C.',
    descriptionAr: 'سبيكة فائقة قابلة للتصليد الترسيبي تحتفظ بمتانة زحف هائلة عند درجات حرارة مرتفعة في محركات الصواريخ والتوربينات.',
    applications: ['Jet engine turbine disks', 'Rocket engine injectors', 'Nuclear fuel element spacers', 'Deepwater high-pressure oil tools'],
    composition: { Ni: '50-55%', Cr: '17-21%', Fe: 'Balance', Nb: '4.75-5.5%', Mo: '2.8-3.3%' },
    isDemonstration: true,
    dataSource: 'Special Metals Inconel 718 Technical Data / AMS 5662. Demonstration data.',
  },
  {
    id: 'al-7075-t6',
    name: 'Aerospace Aluminum 7075-T6',
    nameAr: 'ألومنيوم الطيران فائق المتانة 7075-T6',
    designation: 'Al 7075-T6 (UNS A97075)',
    category: 'alloys',
    subCategory: 'Aluminum Alloys',
    formula: 'Al-Zn-Mg-Cu',
    density: 2.81,
    hardness: { value: 150, scale: 'HV', approxHV: 150 },
    tensileStrength: 572,
    yieldStrength: 503,
    elasticModulus: 71.7,
    poissonRatio: 0.33,
    thermalConductivity: 130.0,
    meltingPoint: 635,
    electricalConductivity: 1.9e7,
    corrosionResistance: 'Moderate',
    thermalExpansion: 23.4,
    crystalStructure: 'FCC matrix with η (MgZn2) precipitates',
    maxServiceTemp: 120,
    description: 'Ultra-high-strength zinc-magnesium copper aluminum alloy widely utilized for primary airframe structures requiring high strength-to-weight ratio.',
    descriptionAr: 'سبيكة ألومنيوم فائقة المقاومة مصلدة حرارياً تستخدم بشكل واسع في هياكل الطائرات وتجهيزات التسلق والسباقات.',
    applications: ['Aircraft wing spars & ribs', 'Helicopter rotor hubs', 'High-performance bicycle frames', 'Military missile casings'],
    composition: { Al: 'Balance', Zn: '5.1-6.1%', Mg: '2.1-2.9%', Cu: '1.2-2.0%' },
    isDemonstration: true,
    dataSource: 'MMPDS-01 Handbook / ASTM B209. Demonstration data.',
  },
  {
    id: 'nitinol-55',
    name: 'Nitinol 55 Shape Memory Alloy',
    nameAr: 'سبيكة النيتينول 55 ذات الذاكرة الشكلية',
    designation: 'Nitinol 55 (Ni-Ti 55/45 wt%, UNS N01555)',
    category: 'alloys',
    subCategory: 'Smart Alloys',
    formula: 'NiTi',
    density: 6.45,
    hardness: { value: 230, scale: 'HV', approxHV: 230 },
    tensileStrength: 900,
    yieldStrength: 560,
    elasticModulus: 75,
    poissonRatio: 0.33,
    thermalConductivity: 18.0,
    meltingPoint: 1310,
    electricalConductivity: 1.25e6,
    corrosionResistance: 'Very High',
    thermalExpansion: 11.0,
    crystalStructure: 'Austenite (B2 cubic) ↔ Martensite (B19\' monoclinic)',
    maxServiceTemp: 300,
    description: 'Intermetallic alloy demonstrating reversible thermoelastic martensitic transformation, pseudoelasticity (up to 8% elastic strain recovery), and damping capacity.',
    descriptionAr: 'سبيكة ذكية تمتلك استرجاعاً شكلياً حرارياً ومرونة فائقة تفوق المعادن التقليدية بثمانية أضعاف.',
    applications: ['Self-expanding vascular stents', 'Orthodontic archwires', 'Aerospace thermal actuators', 'Flexible endoscopy tools'],
    composition: { Ni: '55.0-56.0%', Ti: 'Balance' },
    isDemonstration: true,
    dataSource: 'ASTM F2063 Medical Grade NiTi Specification. Demonstration data.',
  },
  {
    id: 'steel-a36',
    name: 'Structural Carbon Steel A36',
    nameAr: 'فولاذ كربوني إنشائي A36',
    designation: 'ASTM A36 (UNS K02600)',
    category: 'alloys',
    subCategory: 'Structural Steels',
    formula: 'Fe-C-Mn',
    density: 7.85,
    hardness: { value: 140, scale: 'HV', approxHV: 140 },
    tensileStrength: 450,
    yieldStrength: 250,
    elasticModulus: 200,
    poissonRatio: 0.29,
    thermalConductivity: 51.9,
    meltingPoint: 1480,
    electricalConductivity: 6.5e6,
    corrosionResistance: 'Low',
    thermalExpansion: 12.0,
    crystalStructure: 'BCC (Ferrite, α-Fe) + Pearlite',
    maxServiceTemp: 450,
    description: 'The most commonly used mild structural steel, characterized by excellent weldability, ductility, and high structural reliability in civil engineering.',
    descriptionAr: 'فولاذ إنشائي خفيف واسع الانتشار يمتاز بقابلية لحام ممتازة ومطيلية عالية في الجسور والمباني الإنشائية.',
    applications: ['Civil building columns & beams', 'Highway bridge girders', 'Machinery baseplates', 'Bolted structural frames'],
    composition: { Fe: 'Balance', C: '0.25-0.29%', Mn: '0.80-1.20%', Si: '0.40% max' },
    isDemonstration: true,
    dataSource: 'ASTM A36 / AISC Steel Construction Manual. Demonstration data.',
  },

  // ==========================================
  // 3. CERAMICS (Technical & Advanced Ceramics)
  // ==========================================
  {
    id: 'sic-alpha',
    name: 'Silicon Carbide (Alpha)',
    nameAr: 'كربيد السيليكون - ألفا',
    designation: 'SiC-α Sintered (6H Polytype)',
    category: 'ceramics',
    subCategory: 'Non-Oxide Ceramics',
    formula: 'SiC',
    density: 3.21,
    hardness: { value: 2600, scale: 'HV', approxHV: 2600 },
    tensileStrength: 450,
    yieldStrength: 3900, // compressive/yield equivalent
    elasticModulus: 410,
    poissonRatio: 0.16,
    thermalConductivity: 120.0,
    meltingPoint: 2730, // decomposition
    electricalConductivity: 100.0, // semiconductor grade
    corrosionResistance: 'Excellent',
    thermalExpansion: 4.0,
    crystalStructure: 'Hexagonal wurtzite (6H polytype)',
    maxServiceTemp: 1600,
    description: 'Extreme hardness covalent ceramic with high thermal conductivity, low thermal expansion, and exceptional resistance to erosion, sliding wear, and chemical attack up to 1600°C.',
    descriptionAr: 'خزف تساهمي فائق الصلادة والتوصيل الحراري ومقاوم للتآكل الاحتكاكي والكيميائي في درجات الحرارة القصوى.',
    applications: ['Mechanical face seals', 'Bulletproof ballistic armor plates', 'Turbine nozzle vanes', 'Wafer processing chucks'],
    composition: { Si: '70.0%', C: '30.0%' },
    isDemonstration: true,
    dataSource: 'NIST Structural Ceramics Database / CoorsTek Technical Data. Demonstration data.',
  },
  {
    id: 'alumina-al2o3',
    name: 'High-Purity Alumina 99.8%',
    nameAr: 'ألومينا عالية النقاوة 99.8%',
    designation: 'α-Al₂O₃ 99.8% (Corundum)',
    category: 'ceramics',
    subCategory: 'Oxide Ceramics',
    formula: 'Al2O3',
    density: 3.98,
    hardness: { value: 1750, scale: 'HV', approxHV: 1750 },
    tensileStrength: 300,
    yieldStrength: 3000,
    elasticModulus: 380,
    poissonRatio: 0.22,
    thermalConductivity: 30.0,
    meltingPoint: 2072,
    electricalConductivity: 1.0e-12, // supreme dielectric insulator
    corrosionResistance: 'Excellent',
    thermalExpansion: 8.1,
    crystalStructure: 'Rhombohedral / Hexagonal close-packed oxygen',
    maxServiceTemp: 1700,
    description: 'Dense technical ceramic possessing supreme electrical insulation, high dielectric strength, elevated hardness, and refractory chemical inertness.',
    descriptionAr: 'خزف تقني كثيف يمتاز بعزل كهربائي فائق وقوة عازلية وصلادة ومقاومة للمصاهير الحمضية.',
    applications: ['High-power electronic substrates', 'Wear-resistant slurry pump sleeves', 'Laser cavity insulators', 'Spark plug insulators'],
    composition: { Al2O3: '99.8%', SiO2: '0.08%', Na2O: '0.04%' },
    isDemonstration: true,
    dataSource: 'Ceradyne / Morgan Advanced Materials Technical Data. Demonstration data.',
  },
  {
    id: 'zirconia-ytzp',
    name: 'Yttria-Stabilized Zirconia (3Y-TZP)',
    nameAr: 'زركونيا مثبتة بالإيتريا (3Y-TZP)',
    designation: '3Y-TZP (3 mol% Y2O3 Tetragonal Polycrystal)',
    category: 'ceramics',
    subCategory: 'Transformation Toughened Ceramics',
    formula: 'ZrO2-3mol% Y2O3',
    density: 6.05,
    hardness: { value: 1300, scale: 'HV', approxHV: 1300 },
    tensileStrength: 850,
    yieldStrength: 2000,
    elasticModulus: 210,
    poissonRatio: 0.31,
    thermalConductivity: 2.2,
    meltingPoint: 2715,
    electricalConductivity: 1.0e-8,
    corrosionResistance: 'Excellent',
    thermalExpansion: 10.5,
    crystalStructure: 'Metastable Tetragonal (t-phase) undergoes stress-induced transformation to Monoclinic (m-phase)',
    maxServiceTemp: 1000,
    description: 'Often called "ceramic steel", it leverages stress-induced phase transformation to arrest crack propagation, giving highest fracture toughness among monolithic ceramics.',
    descriptionAr: 'يطلق عليه "الفولاذ السيراميكي" لامتلاكه آلية تحول طوري تمنع انتشار الشقوق وتكسبه متانة كسر غير مسبوقة.',
    applications: ['All-ceramic dental crowns', 'Surgical femoral heads', 'Ceramic cutting knives', 'Thermal barrier coatings'],
    composition: { ZrO2: '94.5%', Y2O3: '5.2%', Al2O3: '0.25%' },
    isDemonstration: true,
    dataSource: 'Tosoh Zirconia Technical Specification / ISO 13356. Demonstration data.',
  },
  {
    id: 'silicon-nitride',
    name: 'Silicon Nitride (Hot Pressed)',
    nameAr: 'نيتريد السيليكون المكبوس على الساخن',
    designation: 'Si₃N₄ Bearing Grade',
    category: 'ceramics',
    subCategory: 'Non-Oxide Ceramics',
    formula: 'Si3N4',
    density: 3.25,
    hardness: { value: 1600, scale: 'HV', approxHV: 1600 },
    tensileStrength: 800,
    yieldStrength: 2800,
    elasticModulus: 320,
    poissonRatio: 0.26,
    thermalConductivity: 33.0,
    meltingPoint: 1900,
    electricalConductivity: 1.0e-11,
    corrosionResistance: 'Excellent',
    thermalExpansion: 3.2,
    crystalStructure: 'β-Si3N4 Hexagonal with interlocking needle-like grains',
    maxServiceTemp: 1200,
    description: 'High-toughness structural ceramic with low density, low coefficient of friction, high thermal shock resistance, and capability for high-speed ceramic ball bearings.',
    descriptionAr: 'خزف بنيوي فائق التحمل للصدمات الحرارية والاحتكاك، معتمد في محامل الكرات الفائقة السرعة بمحركات الطائرات.',
    applications: ['Hybrid ceramic ball bearings', 'Diesel glow plugs', 'Weld location pins', 'Gas turbine rotors'],
    composition: { Si3N4: '95%', Y2O3: '3%', Al2O3: '2%' },
    isDemonstration: true,
    dataSource: 'Kyocera Technical Ceramics Database. Demonstration data.',
  },

  // ==========================================
  // 4. POLYMERS (Thermoplastics & Thermosets)
  // ==========================================
  {
    id: 'peek-polymer',
    name: 'Polyether Ether Ketone (PEEK)',
    nameAr: 'بولي إيثر إيثر كيتون (PEEK)',
    designation: 'PEEK Unfilled (Victrex 450G)',
    category: 'polymers',
    subCategory: 'High-Performance Thermoplastics',
    formula: '(C19H12O3)n',
    density: 1.32,
    hardness: { value: 85, scale: 'Shore D', approxHV: 35 },
    tensileStrength: 100,
    yieldStrength: 95,
    elasticModulus: 3.8,
    poissonRatio: 0.40,
    thermalConductivity: 0.25,
    meltingPoint: 343,
    electricalConductivity: 1.0e-14,
    corrosionResistance: 'Excellent',
    thermalExpansion: 47.0,
    crystalStructure: 'Semi-crystalline thermoplastic (~35% crystallinity)',
    maxServiceTemp: 260,
    description: 'Premier ultra-performance thermoplastic delivering high continuous operating temperature, gamma radiation resistance, and near-universal chemical inertness.',
    descriptionAr: 'بوليمر حراري فائق الأداء يتحمل درجات حرارة تصل إلى 260° مئوية مع مقاومة استثنائية للإشعاع والمذيبات العضوية.',
    applications: ['Spinal fusion cage implants', 'Aerospace electrical connectors', 'Downhole oil & gas valve seats', 'Semiconductor wafer carriers'],
    composition: { PEEK: '100%' },
    isDemonstration: true,
    dataSource: 'Victrex PEEK Material Properties Guide / ASTM D4000. Demonstration data.',
  },
  {
    id: 'ptfe-teflon',
    name: 'Polytetrafluoroethylene (PTFE)',
    nameAr: 'بولي تترافلورو إيثيلين (تيفلون)',
    designation: 'PTFE Virgin (Teflon / DuPont)',
    category: 'polymers',
    subCategory: 'Fluoropolymers',
    formula: '(C2F4)n',
    density: 2.16,
    hardness: { value: 58, scale: 'Shore D', approxHV: 15 },
    tensileStrength: 30,
    yieldStrength: 15,
    elasticModulus: 0.5,
    poissonRatio: 0.46,
    thermalConductivity: 0.25,
    meltingPoint: 327,
    electricalConductivity: 1.0e-17,
    corrosionResistance: 'Excellent',
    thermalExpansion: 135.0,
    crystalStructure: 'Helical polymer chain, high crystallinity (60-80%)',
    maxServiceTemp: 260,
    description: 'Fluorocarbon polymer boasting the lowest friction coefficient of any solid, total hydrophobic repelling, and resistance to nearly all acids, bases, and organic solvents.',
    descriptionAr: 'بوليمر فلوروكربوني يمتلك أقل معامل احتكاك بين المواد الصلبة مع خمول كيميائي تام تجاه كافة الأحماض.',
    applications: ['Corrosive chemical gaskets & seals', 'Coaxial cable RF dielectric insulation', 'Non-stick cookware coatings', 'Vascular bypass grafts'],
    composition: { C: '24.0%', F: '76.0%' },
    isDemonstration: true,
    dataSource: 'DuPont Fluoropolymer Handbook. Demonstration data.',
  },
  {
    id: 'polycarbonate-pc',
    name: 'Polycarbonate (Lexan)',
    nameAr: 'بولي كربونات (ليكسان)',
    designation: 'PC General Purpose (Makrolon / Lexan)',
    category: 'polymers',
    subCategory: 'Engineering Thermoplastics',
    formula: '(C16H14O3)n',
    density: 1.20,
    hardness: { value: 82, scale: 'Shore D', approxHV: 25 },
    tensileStrength: 65,
    yieldStrength: 62,
    elasticModulus: 2.4,
    poissonRatio: 0.37,
    thermalConductivity: 0.20,
    meltingPoint: 155, // Tg glass transition
    electricalConductivity: 1.0e-14,
    corrosionResistance: 'Moderate',
    thermalExpansion: 68.0,
    crystalStructure: 'Amorphous polymer (transparent 89% visible light transmission)',
    maxServiceTemp: 125,
    description: 'Transparent engineering thermoplastic celebrated for extraordinary impact resistance (virtually unbreakable), high optical clarity, and dimensional stability.',
    descriptionAr: 'بلاستيك هندسي شفاف ذو مقاومة صدمية هائلة تفوق الزجاج بمائتي ضعف ويستخدم في الحواجز المقاومة للرصاص.',
    applications: ['Bullet-resistant security glazing', 'Astronaut helmet visors', 'Automotive headlight lenses', 'Electronic device enclosures'],
    composition: { Polycarbonate: '100%' },
    isDemonstration: true,
    dataSource: 'SABIC Lexan Resin Data Sheet. Demonstration data.',
  },
  {
    id: 'uhmwpe',
    name: 'Ultra-High-Molecular-Weight Polyethylene',
    nameAr: 'بولي إيثيلين فائق الوزن الجزيئي (UHMWPE)',
    designation: 'UHMWPE (GUR 1020 / Celanese)',
    category: 'polymers',
    subCategory: 'Polyolefins',
    formula: '(C2H4)n, Mw > 3×10^6 g/mol',
    density: 0.935,
    hardness: { value: 65, scale: 'Shore D', approxHV: 18 },
    tensileStrength: 45,
    yieldStrength: 22,
    elasticModulus: 0.9,
    poissonRatio: 0.44,
    thermalConductivity: 0.41,
    meltingPoint: 135,
    electricalConductivity: 1.0e-15,
    corrosionResistance: 'Very High',
    thermalExpansion: 180.0,
    crystalStructure: 'Semi-crystalline with entangled extremely long molecular chains',
    maxServiceTemp: 90,
    description: 'Polymer possessing the highest impact strength and abrasion resistance of any thermoplastic, self-lubricating surface, and complete biocompatibility.',
    descriptionAr: 'بوليمر بسلاسل جزيئية عملاقة يمتاز بأعلى مقاومة للتآكل السطحي بين اللدائن، معتمد في مفاصل الورك والركبة الصناعية.',
    applications: ['Orthopedic total joint prostheses (hip/knee cups)', 'Ballistic Dyneema fiber armor', 'Conveyor chute wear liners', 'Marine dock bumpers'],
    composition: { UHMWPE: '100%' },
    isDemonstration: true,
    dataSource: 'Celanese GUR Technical Brochure / ASTM F648. Demonstration data.',
  },

  // ==========================================
  // 5. COMPOSITES (FRP, CMC, MMC)
  // ==========================================
  {
    id: 'cfrp-epoxy-hm',
    name: 'Carbon Fiber / Epoxy Composite (High Modulus)',
    nameAr: 'مركب ألياف الكربون / الإيبوكسي فائق المعامل',
    designation: 'CFRP HM Unidirectional (Vf = 60%)',
    category: 'composites',
    subCategory: 'Polymer Matrix Composites (PMC)',
    formula: 'Carbon Fiber (PAN) + Toughened Epoxy',
    density: 1.55,
    hardness: { value: 90, scale: 'Shore D', approxHV: 55 },
    tensileStrength: 1850,
    yieldStrength: 1600,
    elasticModulus: 230,
    poissonRatio: 0.28,
    thermalConductivity: 8.5,
    meltingPoint: 180, // Glass transition / degradation
    electricalConductivity: 1.2e4, // semi-conductive carbon fibers
    corrosionResistance: 'Excellent',
    thermalExpansion: -0.2, // near zero longitudinal CTE
    crystalStructure: 'Graphitic microfibrils embedded in thermoset crosslinked polymer network',
    maxServiceTemp: 160,
    description: 'High-modulus carbon fiber embedded in an epoxy matrix delivering higher specific stiffness than titanium or steel, fatigue resistance, and near-zero thermal expansion.',
    descriptionAr: 'مركب إنشائي متقدم يوفر صلابة نوعية تفوق التيتانيوم والفولاذ بأوزان خفيفة وتمدد حراري شبه منعدم في مدارات الفضاء.',
    applications: ['Spacecraft truss structures', 'Commercial aircraft fuselage (B787 / A350)', 'Formula 1 monocoque chassis', 'Wind turbine main spars'],
    composition: { 'Carbon Fiber': '60% vol', Epoxy: '40% vol' },
    isDemonstration: true,
    dataSource: 'Toray Carbon Fibers Technical Manual / MIL-HDBK-17. Demonstration data.',
  },
  {
    id: 'gfrp-epoxy-g10',
    name: 'Glass-Epoxy Laminate G10 / FR4',
    nameAr: 'صفائح الزجاج والإيبوكسي G10 / FR4',
    designation: 'NEMA Grade G10 / FR4',
    category: 'composites',
    subCategory: 'Polymer Matrix Composites (PMC)',
    formula: 'E-Glass Cloth + Brominated Epoxy',
    density: 1.85,
    hardness: { value: 85, scale: 'Shore D', approxHV: 40 },
    tensileStrength: 310,
    yieldStrength: 240,
    elasticModulus: 24,
    poissonRatio: 0.18,
    thermalConductivity: 0.30,
    meltingPoint: 140,
    electricalConductivity: 1.0e-12,
    corrosionResistance: 'Very High',
    thermalExpansion: 14.0,
    crystalStructure: 'Amorphous woven glass filament fabric in cured cross-linked epoxy',
    maxServiceTemp: 130,
    description: 'Continuous woven E-glass cloth impregnated with thermoset epoxy binder, widely adopted as the international substrate standard for printed circuit boards (PCBs).',
    descriptionAr: 'مركب الألياف الزجاجية المنسوجة مع راتنج الإيبوكسي، المرجع الصناعي العالمي لركائز لوحات الدوائر الإلكترونية المطبوعة.',
    applications: ['Printed circuit board (PCB) substrates', 'High-voltage electrical terminal boards', 'Cryogenic support struts', 'Knife handle scales'],
    composition: { 'E-Glass': '55% wt', Epoxy: '45% wt' },
    isDemonstration: true,
    dataSource: 'NEMA Industrial Laminate Standards / ASTM D709. Demonstration data.',
  },
  {
    id: 'cmc-sic-sic',
    name: 'Ceramic Matrix Composite (SiC/SiC)',
    nameAr: 'مركب المصفوفة الخزفية (SiC/SiC)',
    designation: 'SiC Fiber / Chemical Vapor Infiltrated SiC Matrix',
    category: 'composites',
    subCategory: 'Ceramic Matrix Composites (CMC)',
    formula: 'SiC(f)/SiC(m)',
    density: 2.65,
    hardness: { value: 2200, scale: 'HV', approxHV: 2200 },
    tensileStrength: 350,
    yieldStrength: 280,
    elasticModulus: 240,
    poissonRatio: 0.18,
    thermalConductivity: 25.0,
    meltingPoint: 2700,
    electricalConductivity: 10.0,
    corrosionResistance: 'Excellent',
    thermalExpansion: 4.2,
    crystalStructure: 'Hi-Nicalon Type S continuous SiC fibers inside nano-crystalline SiC CVI matrix',
    maxServiceTemp: 1350,
    description: 'High-temperature ceramic matrix composite engineered for next-generation jet turbine shrouds, operating at one-third the weight of nickel superalloys and with reduced cooling air requirements.',
    descriptionAr: 'مركب خزفي متطور يعمل بثلث وزن سبائك النيكل ويتحمل درجات حرارة تفوق 1300° مئوية في غرف احتراق المحركات النفاثة.',
    applications: ['Aero-engine turbine shrouds & nozzles (CFM LEAP, GE9X)', 'Nuclear fusion divertor first wall', 'Hypersonic thermal protection leading edges'],
    composition: { SiC: '98%', C: '2%' },
    isDemonstration: true,
    dataSource: 'NASA Glenn Research Center CMC Database / GE Aviation Publications. Demonstration data.',
  },

  // ==========================================
  // 6. SEMICONDUCTORS (Electronic & Optoelectronic)
  // ==========================================
  {
    id: 'silicon-monocrystal',
    name: 'Single Crystal Silicon ⟨100⟩',
    nameAr: 'سيليكون أحادي البلورة ⟨100⟩',
    designation: 'Electronic Grade Si ⟨100⟩ (99.9999999% purity)',
    category: 'semiconductors',
    subCategory: 'Group IV Semiconductors',
    formula: 'Si',
    density: 2.33,
    hardness: { value: 1050, scale: 'HV', approxHV: 1050 },
    tensileStrength: 150,
    yieldStrength: 120,
    elasticModulus: 130, // ⟨100⟩ direction
    poissonRatio: 0.28,
    thermalConductivity: 149.0,
    meltingPoint: 1414,
    electricalConductivity: 4.35e-4, // Undoped intrinsic; dopable up to 1e5 S/m
    corrosionResistance: 'High',
    thermalExpansion: 2.6,
    crystalStructure: 'Diamond Cubic (Fd3m, a = 5.431 Å)',
    maxServiceTemp: 150,
    description: 'The foundation of modern integrated circuit microelectronics and photovoltaic solar cells, grown via the Czochralski process to near-perfect crystal perfection.',
    descriptionAr: 'حجر الأساس لصناعة الرقائق الإلكترونية والمعالجات الدقيقة والخلايا الشمسية بفضل شبكته البلورية الماسية النقية.',
    applications: ['Microprocessors & DRAM chips', 'CMOS image sensors', 'MEMS accelerometers', 'High-efficiency solar cells'],
    composition: { Si: '99.9999999%' },
    isDemonstration: true,
    dataSource: 'Sze Physics of Semiconductor Devices / Ioffe Institute Semiconductor Archive. Demonstration data.',
  },
  {
    id: 'gan-semiconductor',
    name: 'Gallium Nitride (GaN Wurtzite)',
    nameAr: 'نيتريد الغاليوم (GaN فورتزيت)',
    designation: 'GaN Wurtzite (Direct Bandgap 3.4 eV)',
    category: 'semiconductors',
    subCategory: 'III-V Wide Bandgap Semiconductors',
    formula: 'GaN',
    density: 6.15,
    hardness: { value: 1200, scale: 'HV', approxHV: 1200 },
    tensileStrength: 350,
    yieldStrength: 300,
    elasticModulus: 295,
    poissonRatio: 0.23,
    thermalConductivity: 130.0,
    meltingPoint: 2500, // under high nitrogen pressure
    electricalConductivity: 1.0e-2, // intrinsic
    corrosionResistance: 'Excellent',
    thermalExpansion: 5.6,
    crystalStructure: 'Hexagonal Wurtzite (P63mc)',
    maxServiceTemp: 500,
    description: 'Wide bandgap (3.4 eV) semiconductor enabling high breakdown voltage, fast electron saturation velocity, and efficient blue/UV photon emission.',
    descriptionAr: 'شبه موصل ذو فجوة نطاق عريضة يتيح شواحن كهربائية فائقة الصغر وكفاءة عالية ومصابيح ليزر زرقاء ومحطات 5G.',
    applications: ['Blue and UV light emitting diodes (LEDs)', 'High-power fast chargers (HEMT)', '5G cellular base station radar', 'Electric vehicle inverters'],
    composition: { Ga: '83.3%', N: '16.7%' },
    isDemonstration: true,
    dataSource: 'Cree / Wolfspeed Technical Documentation. Demonstration data.',
  },
  {
    id: 'gaas-semiconductor',
    name: 'Gallium Arsenide (GaAs)',
    nameAr: 'زرنيخيد الغاليوم (GaAs)',
    designation: 'GaAs Semi-Insulating (Direct Bandgap 1.42 eV)',
    category: 'semiconductors',
    subCategory: 'III-V Compound Semiconductors',
    formula: 'GaAs',
    density: 5.32,
    hardness: { value: 750, scale: 'HV', approxHV: 750 },
    tensileStrength: 100,
    yieldStrength: 80,
    elasticModulus: 85,
    poissonRatio: 0.31,
    thermalConductivity: 55.0,
    meltingPoint: 1238,
    electricalConductivity: 1.0e-6,
    corrosionResistance: 'Moderate',
    thermalExpansion: 5.7,
    crystalStructure: 'Zincblende (Sphalerite, F43m)',
    maxServiceTemp: 350,
    description: 'Direct bandgap compound semiconductor offering electron mobility six times higher than silicon, making it ideal for satellite solar panels and RF amplifiers.',
    descriptionAr: 'شبه موصل بمركب زرنيخي يمتاز بحركية إلكترونية تفوق السيليكون بست مرات في الدوائر الميكروية وتطبيقات الأقمار الصناعية.',
    applications: ['Smartphone RF power amplifiers', 'Near-infrared laser diodes', 'Spacecraft multi-junction solar cells', 'Millimeter wave radar'],
    composition: { Ga: '48.2%', As: '51.8%' },
    isDemonstration: true,
    dataSource: 'Ioffe Physico-Technical Institute Semiconductor Physics. Demonstration data.',
  },
  {
    id: 'diamond-cvd',
    name: 'CVD Polycrystalline Diamond',
    nameAr: 'ألماس اصطناعي مرسب كيميائياً (CVD)',
    designation: 'Optical & Thermal Grade CVD Diamond',
    category: 'semiconductors',
    subCategory: 'Wide-Bandgap Diamond Semiconductors',
    formula: 'C',
    density: 3.52,
    hardness: { value: 10000, scale: 'HV', approxHV: 10000 },
    tensileStrength: 1050,
    yieldStrength: 5000,
    elasticModulus: 1050,
    poissonRatio: 0.10,
    thermalConductivity: 2000.0,
    meltingPoint: 3550, // phase change to graphite under vacuum
    electricalConductivity: 1.0e-14, // ultra-insulator, 5.5 eV bandgap
    corrosionResistance: 'Excellent',
    thermalExpansion: 1.0,
    crystalStructure: 'Diamond Cubic sp3 hybridized carbon lattice',
    maxServiceTemp: 800,
    description: 'The ultimate thermal conductor (5x copper) and hardest known material, providing extreme radiation hardness, optical broadband transparency, and wide bandgap.',
    descriptionAr: 'أعلى مادة في التوصيل الحراري والصلادة في الكون المعروف، يستخدم في مشتتات حرارة الليزر الفائق والنوافذ البصرية عالية الطاقة.',
    applications: ['High-power laser diode heat spreaders', 'Synchrotron X-ray beam windows', 'Precision surgical scalpels', 'Quantum nitrogen-vacancy magnetometers'],
    composition: { C: '>99.99%' },
    isDemonstration: true,
    dataSource: 'Element Six Diamond Technical Guide. Demonstration data.',
  },

  // ==========================================
  // 7. ADVANCED MATERIALS (Nanomaterials, BMG & HEA)
  // ==========================================
  {
    id: 'graphene-multilayer',
    name: 'Graphene Nanoplatelet Film',
    nameAr: 'غشاء صفيحات الجرافين النانوية',
    designation: 'Pristine Multilayer Graphene Film (5-10 layers)',
    category: 'advanced materials',
    subCategory: '2D Nanomaterials',
    formula: 'C',
    density: 2.10,
    hardness: { value: 1500, scale: 'HV', approxHV: 1500 },
    tensileStrength: 2500,
    yieldStrength: 1800,
    elasticModulus: 800,
    poissonRatio: 0.17,
    thermalConductivity: 1500.0,
    meltingPoint: 3652,
    electricalConductivity: 1.0e6,
    corrosionResistance: 'Excellent',
    thermalExpansion: -1.0,
    crystalStructure: 'sp2 hybridized planar hexagonal honeycomb 2D atomic lattice',
    maxServiceTemp: 500,
    description: 'Two-dimensional monolayer allotrope of carbon with ballistic electronic transport, extreme in-plane thermal dissipation, and impermeable barrier properties.',
    descriptionAr: 'مادة ثنائية الأبعاد من ذرات الكربون السداسية تمتاز بتوصيل حراري فائق ومقاومة ميكانيكية استثنائية ونفاذية غازية صفرية.',
    applications: ['Smartphone thermal heat spreader pads', 'Electromagnetic interference (EMI) shielding', 'Lithium-ion battery conductive additives', 'Ultrafiltration desalination membranes'],
    composition: { C: '99.5%' },
    isDemonstration: true,
    dataSource: 'Nature Materials Graphene Review / ISO/TS 80004-13 Nanotechnologies. Demonstration data.',
  },
  {
    id: 'vitreloy-1-bmg',
    name: 'Bulk Metallic Glass (Vitreloy 1)',
    nameAr: 'الزجاج المعدني الكتلي (فيتريلوي 1)',
    designation: 'Zr41.2Ti13.8Cu12.5Ni10.0Be22.5 (Vitreloy 1)',
    category: 'advanced materials',
    subCategory: 'Amorphous Alloys (BMG)',
    formula: 'Zr-Ti-Cu-Ni-Be',
    density: 6.10,
    hardness: { value: 550, scale: 'HV', approxHV: 550 },
    tensileStrength: 1900,
    yieldStrength: 1850,
    elasticModulus: 96,
    poissonRatio: 0.36,
    thermalConductivity: 4.0,
    meltingPoint: 660, // Tg = 350°C, liquidus = 660°C
    electricalConductivity: 5.0e5,
    corrosionResistance: 'Excellent',
    thermalExpansion: 9.8,
    crystalStructure: 'Amorphous liquid-like atomic structure (no grain boundaries or dislocations)',
    maxServiceTemp: 300,
    description: 'Amorphous alloy devoid of crystalline grain boundaries, exhibiting high elastic strain limit (2%), high yield strength, and net-shape blow-molding capability.',
    descriptionAr: 'سبيكة غير متبلورة خالية من الحدود الحبيبية، تمتاز بمرونة هائلة تصل إلى ضعف المعادن التقليدية مع مقاومة تآكل خدشي فائقة.',
    applications: ['Aerospace spacecraft micrometeorite shields', 'High-end luxury watch cases', 'High-precision gears for space rovers', 'Medical surgical micro-blades'],
    composition: { Zr: '41.2%', Ti: '13.8%', Cu: '12.5%', Ni: '10.0%', Be: '22.5%' },
    isDemonstration: true,
    dataSource: 'Liquidmetal Technologies Data Sheet / Caltech Materials Science. Demonstration data.',
  },
  {
    id: 'cantor-hea',
    name: 'Cantor High-Entropy Alloy (FeCoCrNiMn)',
    nameAr: 'سبيكة كانتور عالية الإنتروبيا (FeCoCrNiMn)',
    designation: 'Equiatomic Fe20Co20Cr20Ni20Mn20 (HEA)',
    category: 'advanced materials',
    subCategory: 'High-Entropy Alloys (HEA)',
    formula: 'FeCoCrNiMn',
    density: 8.05,
    hardness: { value: 180, scale: 'HV', approxHV: 180 },
    tensileStrength: 850,
    yieldStrength: 420,
    elasticModulus: 202,
    poissonRatio: 0.29,
    thermalConductivity: 12.5,
    meltingPoint: 1335,
    electricalConductivity: 9.2e5,
    corrosionResistance: 'Very High',
    thermalExpansion: 14.2,
    crystalStructure: 'Single-phase FCC solid solution stabilized by high configurational entropy',
    maxServiceTemp: 800,
    description: 'Equiatomic multi-principal element alloy that defies classical metallurgy by remaining single-phase FCC, achieving increasing fracture toughness at cryogenic temperatures (-196°C).',
    descriptionAr: 'سبيكة ثورية متعددة العناصر الرئيسة تزداد صلابتها ومقاومتها للكسر كلما انخفضت درجة الحرارة حتى النيتروجين السائل.',
    applications: ['Cryogenic liquefied natural gas (LNG) tanks', 'Hydrogen storage vessel liners', 'Deep-space probe structural frames', 'Radiation-tolerant nuclear cladding'],
    composition: { Fe: '20%', Co: '20%', Cr: '20%', Ni: '20%', Mn: '20%' },
    isDemonstration: true,
    dataSource: 'Acta Materialia Cantor HEA Investigation. Demonstration data.',
  },
  {
    id: 'aerogel-silica',
    name: 'Nanoporous Silica Aerogel',
    nameAr: 'إيروجيل السيليكا النانوي المسامي',
    designation: 'Hydrophobic Silica Aerogel Monolith (98% air)',
    category: 'advanced materials',
    subCategory: 'Nanoporous Super-insulators',
    formula: 'SiO2 (Nanoporous Network)',
    density: 0.10, // ~100 kg/m³
    hardness: { value: 10, scale: 'HV', approxHV: 10 },
    tensileStrength: 2,
    yieldStrength: 1,
    elasticModulus: 0.05,
    poissonRatio: 0.20,
    thermalConductivity: 0.015, // Lower than stationary air!
    meltingPoint: 1200,
    electricalConductivity: 1.0e-16,
    corrosionResistance: 'Very High',
    thermalExpansion: 3.0,
    crystalStructure: 'Amorphous, 3D interconnected silica nanoparticle sponge with 20nm pore size',
    maxServiceTemp: 650,
    description: 'Known as "frozen smoke", it is the world\'s lowest density solid and premier thermal insulator, suppressing gaseous convective and conductive thermal transfer.',
    descriptionAr: 'أخف مادة صلبة في العالم وتسمى "الدخان المجمد"، توفر عزلاً حرارياً خارقاً أدنى من الهواء الساكن نفسه بفضل بنيتها النانوية.',
    applications: ['Mars Rover cosmic thermal insulation', 'Cryogenic rocket propellant tanks', 'High-performance architectural glazing insulation', 'Space cometary dust collectors (NASA Stardust)'],
    composition: { SiO2: '99.0%', 'Hydrophobic Silane': '1.0%' },
    isDemonstration: true,
    dataSource: 'Aspen Aerogels / NASA Jet Propulsion Laboratory. Demonstration data.',
  },
];
